export const LOAD_FORM_QUESTIONS = "LOAD_FORM_QUESTIONS";
export const ADD_QUESTION_ANSWER = "ADD_QUESTION_ANSWER";
export const GO_TO_NEXT_QUESTION = "GO_TO_NEXT_QUESTION";
export const GO_TO_PERVIOUS_QUESTION = "GO_TO_PERVIOUS_QUESTION";
export const SUBMIT_FORM = "SUBMIT_FORM";
export const START_NEW_FORM = "START_NEW_FORM";
